import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import NoiseBg from "@/components/NoiseBg/NoiseBg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--spaceMono",
  adjustFontFallback: false,
  display: "swap",
});

const thunderSemiBold = localFont({
  src: "../../public/fonts/ThunderSemiBold.ttf",
  variable: "--thunderSemiBold",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${spaceMono.className} ${thunderSemiBold.className} `}>
        <NoiseBg>{children}</NoiseBg>
      </body>
    </html>
  );
}
