import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "500", "600", "700"],
  variable: "--inter",
});

const monoBold = localFont({
  src: "../../public/fonts/ApercuMonoProBold.ttf",
  variable: "--monoBold",
  display: "swap",
});

const monoMedium = localFont({
  src: "../../public/fonts/ApercuMonoProMedium.ttf",
  variable: "--monoMedium",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} ${monoBold.className} ${monoMedium.className}`}
      >
        {children}
      </body>
    </html>
  );
}
